apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: acrpractica2.azurecr.io/backend:CP2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: contador-storage
              mountPath: /mnt/data
      volumes:
        - name: contador-storage
          persistentVolumeClaim:
            claimName: webkube-pvc
      imagePullSecrets:
        - name: acr-secret

